package CalcApp;


/**
* CalcApp/CalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Saturday, 3 May, 2025 2:35:27 PM IST
*/

public interface CalcOperations 
{
  int add (int a, int b);
  int sub (int a, int b);
} // interface CalcOperations
